from bcc import BPF

# define BPF program
# This program acts as a callback. Any time any of the syscalls attached to b occur, the hello function is executed
prog = """

// Some kind of struct
// Not sure what needs to go in it
struct bpf_map_def my_map = {
	.type = BPF_MAP_TYPE_PERF_EVENT_ARRAY,
	.key_size = sizeof(int),
	.value_size = sizeof(u32),
	.max_entries = 32,
};

BPF_PERF_OUTPUT(events);


int hello(void *ctx) {
    // bpf_trace_printk("hello world!\\n");
    u64 key = bpf_get_smp_processor_id();

    // 1. This is the function you're trying to use:
    u64 count =  bpf_perf_event_read(&my_map, BPF_F_CURRENT_CPU);

    
    // 2. Record value of perf event "mem-stores"

    // 3. Print to console 
    events.perf_submit(ctx, &key, sizeof(key));


    return 0;
}
"""

# load BPF program
b = BPF(text=prog)

##################
#### SYSCALLS ####
##################
# Taken from http://man7.org/linux/man-pages/man2/syscalls.2.html

# b.attach_kprobe(event=b.get_syscall_fnname("_llseek"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("_newselect"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("_sysctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("accept"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("accept4"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("access"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("acct"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("add_key"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("adjtimex"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("alarm"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("alloc_hugepages"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("bdflush"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("bind"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("bpf"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("brk"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("cacheflush"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("capget"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("capset"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("chdir"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("chmod"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("chown"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("chown32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("chroot"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("clock_adjtime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("clock_getres"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("clock_gettime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("clock_nanosleep"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("clock_settime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("clone"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("close"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("connect"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("copy_file_range"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("creat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("create_module"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("delete_module"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("dup"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("dup2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("dup3"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("epoll_create"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("epoll_create1"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("epoll_ctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("epoll_pwait"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("epoll_wait"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("eventfd"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("eventfd2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("execve"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("execveat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("exit"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("exit_group"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("faccessat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fadvise64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fadvise64_64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fallocate"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fanotify_init"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fanotify_mark"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fchdir"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fchmod"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fchmodat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fchown"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("fchown32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fchownat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fcntl"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("fcntl64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fdatasync"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fgetxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("flock"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fork"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("free_hugepages"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fremovexattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fstat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("fstat64"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("fstatat64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fstatfs"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fstatfs64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("fsync"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ftruncate"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("ftruncate64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("futex"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("futimesat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("get_kernel_syms"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("get_mempolicy"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("get_robust_list"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("get_thread_area"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getcpu"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getcwd"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getdents"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getdents64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getegid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getegid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("geteuid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("geteuid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getgid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getgid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getgroups"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getgroups32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getitimer"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getpeername"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getpagesize"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getpgid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getpgrp"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getpid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getppid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getpriority"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getrandom"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getresgid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getresgid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getresuid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getresuid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getrlimit"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getrusage"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getsid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getsockname"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getsockopt"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("gettid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("gettimeofday"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getuid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getuid32"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("getunwind"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("getxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("init_module"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("inotify_add_watch"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("inotify_init"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("inotify_init1"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("inotify_rm_watch"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("io_cancel"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("io_destroy"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("io_getevents"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("io_setup"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("io_submit"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ioctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ioperm"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("iopl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ioprio_get"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ioprio_set"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ipc"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("kcmp"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("kern_features"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("kexec_file_load"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("kexec_load"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("keyctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("kill"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lchown"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("lchown32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lgetxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("link"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("linkat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("listen"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("listxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("llistxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lookup_dcookie"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lremovexattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lseek"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lsetxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("lstat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("lstat64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("madvise"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mbind"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("membarrier"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("memfd_create"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("migrate_pages"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mincore"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mkdir"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mkdirat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mknod"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mknodat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mlock"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mlock2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mlockall"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mmap"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("mmap2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("modify_ldt"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mount"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("move_pages"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mprotect"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mq_getsetattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mq_notify"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mq_open"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mq_timedreceive"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mq_timedsend"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mq_unlink"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("mremap"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("msgctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("msgget"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("msgrcv"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("msgsnd"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("msync"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("munlock"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("munlockall"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("munmap"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("name_to_handle_at"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("nanosleep"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("nfsservctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("nice"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("oldfstat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("oldlstat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("oldolduname"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("oldstat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("olduname"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("open"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("open_by_handle_at"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("openat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pause"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pciconfig_iobase"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pciconfig_read"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pciconfig_write"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("perf_event_open"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("personality"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("perfctr"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("perfmonctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pipe"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pipe2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pivot_root"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pkey_alloc"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pkey_free"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pkey_mprotect"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("poll"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("ppc_rtas"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("ppc_swapcontext"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ppoll"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("prctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pread64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("preadv"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("preadv2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("prlimit64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("process_vm_readv"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("process_vm_writev"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pselect6"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ptrace"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pwrite64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pwritev"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("pwritev2"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("query_module"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("quotactl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("read"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("readahead"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("readdir"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("readlink"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("readlinkat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("readv"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("reboot"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("recv"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("recvfrom"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("recvmsg"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("recvmmsg"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("remap_file_pages"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("removexattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rename"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("renameat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("renameat2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("request_key"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("restart_syscall"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rmdir"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigaction"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigpending"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigprocmask"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigqueueinfo"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigreturn"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigsuspend"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_sigtimedwait"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("rt_tgsigqueueinfo"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("s390_runtime_instr"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("s390_pci_mmio_read"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("s390_pci_mmio_write"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("s390_sthyi"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_get_priority_max"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_get_priority_min"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_getaffinity"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_getattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_getparam"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_getscheduler"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_rr_get_interval"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_setaffinity"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_setattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_setparam"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_setscheduler"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sched_yield"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("seccomp"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("select"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("semctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("semget"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("semop"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("semtimedop"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("send"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sendfile"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sendfile64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sendmmsg"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sendmsg"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sendto"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("set_mempolicy"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("set_robust_list"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("set_thread_area"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("set_tid_address"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setdomainname"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setfsgid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setgsgid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setfsuid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setfsuid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setgid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setgid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setgroups"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setgroups32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sethostname"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setitimer"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setns"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setpgid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setpriority"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setregid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setregid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setresgid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setresgid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setresuid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setresuid32"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setreuid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setrlimit"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setsid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setsockopt"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("settimeofday"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setuid"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setuid32"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("setup"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("setxattr"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sgetmask"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("shmat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("shmctl"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("shmdt"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("shmget"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("shutdown"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("sigaction"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sigaltstack"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("signal"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("signalfd"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("signalfd64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sigpending"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sigprocmask"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("sigreturn"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sigsuspend"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("socket"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("socketcall"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("socketpair"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("splice"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("spu_create"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("spu_run"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ssetmask"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("stat"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("stat64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("statfs"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("statfs64"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("statx"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("stime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("subpage_prot"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("swapoff"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("swapon"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("symlink"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("symlinkat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sync"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sync_file_range"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sync_file_range2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("syncfs"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sysfs"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("sysinfo"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("syslog"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("tee"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("tgkill"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("time"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timer_create"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timer_delete"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timer_getoverrun"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timer_gettime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timer_settime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timerfd_create"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timerfd_gettime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("timerfd_settime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("times"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("tkill"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("truncate"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("truncate64"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("ugetrlimit"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("umask"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("umount"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("umount2"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("uname"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("unlink"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("unlinkat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("unshare"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("uselib"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("ustat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("userfaultfd"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("utime"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("utimensat"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("utimes"), fn_name="hello")
# b.attach_kprobe(event=b.get_syscall_fnname("utrap_install"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("vfork"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("vhangup"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("vm86old"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("vm86"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("vmsplice"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("wait4"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("waitid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("waitpid"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("write"), fn_name="hello")
b.attach_kprobe(event=b.get_syscall_fnname("writev"), fn_name="hello")

# Read bpf api 
# github.com/iovisor/bcc/blob/master/src/cc/api/bpf.h
# Read PyDocs for bcc/BPF

# print header
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "MESSAGE"))

# format output
# while 1:
#     try:
#         (task, pid, cpu, flags, ts, msg) = b.trace_fields()
#     except ValueError:
#         continue
#     print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))

start = 0
def print_event(cpu, data, size):
    global start
    event = ct.cast(data, ct.POINTER(Data)).contents
    if start == 0:
            start = event.ts
    time_s = (float(event.ts - start)) / 1000000000
    print("%-18.9f %-16s %-6d %s" % (time_s, event.comm, event.pid,
        "Hello, perf_output!"))

b["events"].open_perf_buffer(print_event)
while 1:
    b.perf_buffer_poll()